FROM kong:latest

ENV KONG_DATABASE=postgres
ENV KONG_PG_HOST=${POSTGRES_HOST}
ENV KONG_PG_USER=${POSTGRES_USER}
ENV KONG_PG_PASSWORD=${POSTGRES_PASSWORD}
ENV KONG_PG_DATABASE=${POSTGRES_DB}

EXPOSE 8000 8443 8001 8444

CMD ["kong", "docker-start"]
